swagger: "2.0"
info:
  description: From the ToDo list tutorial on goswagger.io
  title: A ToDo list application
  version: 1.0.0
consumes:
  - application//io.goswagger.examples.todo-list.v1+json
produces:
  - application//io.goswagger.examples.todo.list.v1+json
schemes:
  - http

# Models
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

# Endpoints
paths:
  /:
    get:
      tags:
        - todos
      operationId: find_todos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: List the ToDo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
